In [12]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from collections import Counter

In [13]:
data = pd.read_csv('../input/imdb-data/movie_bd_v5.csv')
data.sample(5)

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year
679,tt0462465,50000000,7033683,Outlander,Jim Caviezel|Sophia Myles|Jack Huston|Ron Perl...,Howard McCain,It destroyed his world. He won't let it destro...,"During the reign of the Vikings, a man from an...",115,Fantasy|Action|Science Fiction,Ascendant Pictures|Rising Star|VIP Medienfonds...,4/24/2008,6.0,2008
1051,tt0431021,14000000,85446075,The Possession,Jeffrey Dean Morgan|Natasha Calis|Madison Dave...,Ole Bornedal,Fear The Demon That Doesn't Fear God,A young girl buys an antique box at a yard sal...,92,Horror|Thriller,Ghost House Pictures|North Box Productions,8/30/2012,5.8,2012
214,tt1430612,28000000,68896829,Brick Mansions,Paul Walker|David Belle|RZA|Robert Maillet|Car...,Camille Delamarre,Undercover and never Outgunned,"In a dystopian Detroit, grand houses that once...",90,Action|Crime|Drama,Canal+|EuropaCorp|CinÃ©+|D8,4/22/2014,5.8,2014
165,tt3442006,7000000,2360281,Cake,Jennifer Aniston|Anna Kendrick|William H. Macy...,Daniel Barnz,Forgiveness is a bitter pill to swallow.,After having visions of a member of her suppor...,102,Drama,Echo Films|We're Not Brothers Productions|Cine...,9/7/2014,6.1,2014
831,tt0810922,19000000,6928068,Take Me Home Tonight,Topher Grace|Anna Faris|Dan Fogler|Teresa Palm...,Michael Dowse,Best. Night. Ever.,Recent MIT grad Matt Franklin (Topher Grace) s...,97,Comedy|Drama|Romance,Imagine Entertainment|Rogue Pictures|Relativit...,3/4/2011,6.3,2011

In [14]:
data.describe()

             budget       revenue      runtime  vote_average  release_year
count  1.889000e+03  1.889000e+03  1889.000000   1889.000000   1889.000000
mean   5.431083e+07  1.553653e+08   109.658549      6.140762   2007.860773
std    4.858721e+07  2.146698e+08    18.017041      0.764763      4.468841
min    5.000000e+06  2.033165e+06    63.000000      3.300000   2000.000000
25%    2.000000e+07  3.456058e+07    97.000000      5.600000   2004.000000
50%    3.800000e+07  8.361541e+07   107.000000      6.100000   2008.000000
75%    7.200000e+07  1.782626e+08   120.000000      6.600000   2012.000000
max    3.800000e+08  2.781506e+09   214.000000      8.100000   2015.000000

# Предобработка

In [15]:
answers = {} # создадим словарь для ответов

# тут другие ваши предобработки колонок например:

# add profit column to original dataset
data['profit'] = data.revenue - data.budget

# add month of release to original dataset
data['release_month'] = data.release_date.apply(lambda s: s.split('/')[0])

# add title length to original dataset
data['title_length'] = data.original_title.apply(lambda s: len(s))

# add overview words count to original dataset
data['overview_words_count'] = data.overview.apply(lambda s: len(s.split(' ')))

# make dataset with exploded genres
data_genres_exploded = data.copy()
data_genres_exploded['genres'] = data_genres_exploded.genres.apply(lambda s: s.split('|'))
data_genres_exploded = data_genres_exploded.explode('genres')

# make dataset with exploded director (hmm...)
data_director_exploded = data.copy()
data_director_exploded['director'] = data_director_exploded.director.apply(lambda s: s.split('|'))
data_director_exploded = data_director_exploded.explode('director')

# make dataset with director and genres exploded
data_director_genres_exploded = data_director_exploded.copy()
data_director_genres_exploded['genres'] = data_director_genres_exploded.genres.apply(lambda s: s.split('|'))
data_director_genres_exploded = data_director_genres_exploded.explode('genres')

# make dataset with exploded cast
data_cast_exploded = data.copy()
data_cast_exploded['cast2'] = data['cast']
data_cast_exploded['cast'] = data_cast_exploded.cast.apply(lambda s: s.split('|'))
data_cast_exploded = data_cast_exploded.explode('cast')

# make dataset with cast and genres exploded
data_cast_genres_exploded = data_cast_exploded.copy()
data_cast_genres_exploded['genres'] = data_cast_genres_exploded.genres.apply(lambda s: s.split('|'))
data_cast_genres_exploded = data_cast_genres_exploded.explode('genres')

# make dataset with production_companies exploded
data_production_companies_exploded = data.copy()
data_production_companies_exploded['production_companies'] = data_production_companies_exploded.production_companies.apply(lambda s: s.split('|'))
data_production_companies_exploded = data_production_companies_exploded.explode('production_companies')

# make dataset with even more exploded cast
data_cast_exploded['cast2'] = data_cast_exploded.cast2.apply(lambda s: s.split('|'))
data_cast_exploded2 = data_cast_exploded.explode('cast2')

# 1. У какого фильма из списка самый большой бюджет?

Использовать варианты ответов в коде решения запрещено.    
Вы думаете и в жизни у вас будут варианты ответов?)

In [16]:
# в словарь вставляем номер вопроса и ваш ответ на него
# Пример: 
answers['1'] = '2. Spider-Man 3 (tt0413300)'
# запишите свой вариант ответа
answers['1'] = '5. Pirates of the Caribbean: On Stranger Tides (tt1298650)'
# +
# если ответили верно, можете добавить комментарий со значком "+"

In [17]:
# тут пишем ваш код для решения данного вопроса:
data.sort_values('budget', ascending=False).head(1)

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit,release_month,title_length,overview_words_count
723,tt1298650,380000000,1021683000,Pirates of the Caribbean: On Stranger Tides,Johnny Depp|PenÃ©lope Cruz|Geoffrey Rush|Ian M...,Rob Marshall,Live Forever Or Die Trying.,Captain Jack Sparrow crosses paths with a woma...,136,Adventure|Action|Fantasy,Walt Disney Pictures|Jerry Bruckheimer Films|M...,5/11/2011,6.3,2011,641683000,5,43,75

ВАРИАНТ 2

In [18]:
# можно добавлять разные варианты решения

# 2. Какой из фильмов самый длительный (в минутах)?

In [19]:
# думаю логику работы с этим словарем вы уже поняли, 
# по этому не буду больше его дублировать
answers['2'] = '2. Gods and Generals (tt0279111)'
# +

In [20]:
data.sort_values('runtime', ascending=False).head(1)

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit,release_month,title_length,overview_words_count
1157,tt0279111,56000000,12923936,Gods and Generals,Stephen Lang|Jeff Daniels|Robert Duvall|Kevin ...,Ronald F. Maxwell,The nations heart was touched by...,The film centers mostly around the personal an...,214,Drama|History|War,Turner Pictures|Antietam Filmworks,2/21/2003,5.8,2003,-43076064,2,17,48

# 3. Какой из фильмов самый короткий (в минутах)?

In [21]:
answers['3'] = '3. Winnie the Pooh (tt1449283)'

In [22]:
data.sort_values('runtime', ascending=False).tail(1)

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit,release_month,title_length,overview_words_count
768,tt1449283,30000000,14460000,Winnie the Pooh,Jim Cummings|Travis Oates|Jim Cummings|Bud Luc...,Stephen Anderson|Don Hall,Oh Pooh.,"During an ordinary day in Hundred Acre Wood, W...",63,Animation|Family,Walt Disney Pictures|Walt Disney Animation Stu...,4/13/2011,6.8,2011,-15540000,4,15,52

# 4. Какова средняя длительность фильмов?

In [23]:
answers['4'] = '2. 110'
# +

In [24]:
round(data.runtime.mean())

110

# 5. Каково медианное значение длительности фильмов?

In [25]:
answers['5'] = '1. 107'
# +

In [26]:
round(data.runtime.median())

107

# 6. Какой самый прибыльный фильм?
#### Внимание! Здесь и далее под «прибылью» или «убытками» понимается разность между сборами и бюджетом фильма. (прибыль = сборы - бюджет) в нашем датасете это будет (profit = revenue - budget)

In [27]:
answers['6'] = '5. Avatar (tt0499549)'
# +

In [28]:
data.sort_values('profit', ascending=False).head(1)

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit,release_month,title_length,overview_words_count
239,tt0499549,237000000,2781505847,Avatar,Sam Worthington|Zoe Saldana|Sigourney Weaver|S...,James Cameron,Enter the World of Pandora.,"In the 22nd century, a paraplegic Marine is di...",162,Action|Adventure|Fantasy|Science Fiction,Ingenious Film Partners|Twentieth Century Fox ...,12/10/2009,7.1,2009,2544505847,12,6,28

# 7. Какой фильм самый убыточный?

In [29]:
answers['7'] = '5. The Lone Ranger (tt1210819)'
# +

In [30]:
data.sort_values('profit', ascending=False).tail(1)

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit,release_month,title_length,overview_words_count
1245,tt1210819,255000000,89289910,The Lone Ranger,Johnny Depp|Armie Hammer|William Fichtner|Hele...,Gore Verbinski,Never Take Off the Mask,The Texas Rangers chase down a gang of outlaws...,149,Action|Adventure|Western,Walt Disney Pictures|Jerry Bruckheimer Films|I...,7/3/2013,6.0,2013,-165710090,7,15,68

# 8. У скольких фильмов из датасета объем сборов оказался выше бюджета?

In [31]:
answers['8'] = '1. 1478'
# +

In [32]:
len(data[data.profit > 0])

1478

# 9. Какой фильм оказался самым кассовым в 2008 году?

In [33]:
answers['9'] = '4. The Dark Knight (tt0468569)'
# +

In [34]:
data[data.release_year == 2008].sort_values('revenue', ascending=False).head(1)

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit,release_month,title_length,overview_words_count
599,tt0468569,185000000,1001921825,The Dark Knight,Christian Bale|Michael Caine|Heath Ledger|Aaro...,Christopher Nolan,Why So Serious?,Batman raises the stakes in his war on crime. ...,152,Drama|Action|Crime|Thriller,DC Comics|Legendary Pictures|Warner Bros.|Syncopy,7/16/2008,8.1,2008,816921825,7,15,67

# 10. Самый убыточный фильм за период с 2012 по 2014 г. (включительно)?

In [35]:
answers['10'] = '5. The Lone Ranger (tt1210819)'
# +

In [36]:
data[(data.release_year >= 2012) & (data.release_year <= 2014)].sort_values('profit', ascending=False).tail(1)

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit,release_month,title_length,overview_words_count
1245,tt1210819,255000000,89289910,The Lone Ranger,Johnny Depp|Armie Hammer|William Fichtner|Hele...,Gore Verbinski,Never Take Off the Mask,The Texas Rangers chase down a gang of outlaws...,149,Action|Adventure|Western,Walt Disney Pictures|Jerry Bruckheimer Films|I...,7/3/2013,6.0,2013,-165710090,7,15,68

# 11. Какого жанра фильмов больше всего?

In [37]:
answers['11'] = '3. Drama'
# +

In [38]:
# эту задачу тоже можно решать разными подходами, попробуй реализовать разные варианты
# если будешь добавлять функцию - выноси ее в предобработку что в начале
data_genres_exploded.value_counts('genres').head(1)

genres
Drama    782
dtype: int64

ВАРИАНТ 2

# 12. Фильмы какого жанра чаще всего становятся прибыльными?

In [39]:
answers['12'] = '1. Drama'
# +

In [40]:
data_genres_exploded[data_genres_exploded.profit > 0].value_counts('genres').head(1)

genres
Drama    560
dtype: int64

# 13. У какого режиссера самые большие суммарные кассовые сборы?

In [41]:
answers['13'] = '5. Peter Jackson'
# +

In [42]:
data_director_exploded.groupby(['director']).revenue.sum().reset_index().sort_values('revenue', ascending=False).head(1)

          director     revenue
727  Peter Jackson  6490593685

# 14. Какой режисер снял больше всего фильмов в стиле Action?

In [43]:
answers['14'] = '3. Robert Rodriguez'
# +

In [44]:
data_director_genres_exploded[data_director_genres_exploded.genres == 'Action'].groupby(['director']).genres.count().reset_index().sort_values('genres', ascending=False).head(1)

             director  genres
296  Robert Rodriguez       9

# 15. Фильмы с каким актером принесли самые высокие кассовые сборы в 2012 году?

In [45]:
answers['15'] = '3. Chris Hemsworth'
# +

In [46]:
data_cast_exploded[data_cast_exploded.release_year == 2012].groupby(['cast']).revenue.sum().reset_index().sort_values('revenue', ascending=False).head(1)

               cast     revenue
77  Chris Hemsworth  2027450773

# 16. Какой актер снялся в большем количестве высокобюджетных фильмов?

In [47]:
answers['16'] = '3. Matt Damon'
# +

In [48]:
data_cast_exploded[data_cast_exploded.budget > data_cast_exploded.budget.mean()].groupby(['cast']).imdb_id.count().reset_index().sort_values('imdb_id', ascending=False).head(1)

           cast  imdb_id
965  Matt Damon       18

# 17. В фильмах какого жанра больше всего снимался Nicolas Cage?

In [49]:
answers['17'] = '2. Action'
# +

In [50]:
data_cast_genres_exploded[data_cast_genres_exploded.cast == 'Nicolas Cage'].value_counts('genres').head(1)

genres
Action    17
dtype: int64

# 18. Самый убыточный фильм от Paramount Pictures

In [51]:
answers['18'] = '1. K-19: The Widowmaker (tt0267626)'
# +

In [52]:
data_production_companies_exploded[data_production_companies_exploded.production_companies == 'Paramount Pictures'].sort_values('profit').head(1)

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit,release_month,title_length,overview_words_count
925,tt0267626,100000000,35168966,K-19: The Widowmaker,Harrison Ford|Liam Neeson|Peter Sarsgaard|Joss...,Kathryn Bigelow,Fate has found its hero.,When Russia's first nuclear submarine malfunct...,138,Thriller|Drama|History,Paramount Pictures,7/19/2002,6.0,2002,-64831034,7,20,23

# 19. Какой год стал самым успешным по суммарным кассовым сборам?

In [53]:
answers['19'] = '5. 2015'
# +

In [54]:
data.groupby('release_year').revenue.sum().reset_index().sort_values('revenue', ascending=False).head(1)

    release_year      revenue
15          2015  25449202382

# 20. Какой самый прибыльный год для студии Warner Bros?

In [55]:
answers['20'] = '1. 2014'
# +

In [56]:
data_production_companies_exploded[data_production_companies_exploded.production_companies.str.contains("Warner", na=False)].groupby('release_year').profit.sum().reset_index().sort_values('profit', ascending=False).head(3)

    release_year      profit
14          2014  2292949646
7           2007  2208217007
8           2008  2134595031

# 21. В каком месяце за все годы суммарно вышло больше всего фильмов?

In [57]:
answers['21'] = '4. Сентябрь'
# +

In [58]:
data.groupby('release_month').imdb_id.count().reset_index().sort_values('imdb_id', ascending=False).head(1)

   release_month  imdb_id
11             9      227

# 22. Сколько суммарно вышло фильмов летом? (за июнь, июль, август)

In [59]:
answers['22'] = '2. 450'
# +

In [60]:
data[data.release_month.isin(['6', '7', '8'])].count().head(1)

imdb_id    450
dtype: int64

# 23. Для какого режиссера зима – самое продуктивное время года?

In [61]:
answers['23'] = '5. Peter Jackson'
# +

In [62]:
data_director_exploded[data_director_exploded.release_month.isin(['11', '12', '1'])].groupby(['director']).imdb_id.count().reset_index().sort_values('imdb_id', ascending=False).head(1)

          director  imdb_id
263  Peter Jackson        8

# 24. Какая студия дает самые длинные названия своим фильмам по количеству символов?

In [63]:
answers['24'] = '5. Four By Two Productions'
# +

In [64]:
data_production_companies_exploded.groupby('production_companies').title_length.median().reset_index().sort_values('title_length', ascending=False).head(1)

        production_companies  title_length
583  Four By Two Productions          83.0

# 25. Описание фильмов какой студии в среднем самые длинные по количеству слов?

In [65]:
answers['25'] = '3. Midnight Picture Show'
# +

In [66]:
data_production_companies_exploded.groupby('production_companies').overview_words_count.median().reset_index().sort_values('overview_words_count', ascending=False).head(1)

       production_companies  overview_words_count
1041  Midnight Picture Show                 175.0

# 26. Какие фильмы входят в 1 процент лучших по рейтингу? 
по vote_average

In [67]:
answers['26'] = '1. Inside Out, The Dark Knight, 12 Years a Slave'
# +

In [68]:
data.sort_values('vote_average', ascending=False).head(round(data.imdb_id.count()/100))

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit,release_month,title_length,overview_words_count
599,tt0468569,185000000,1001921825,The Dark Knight,Christian Bale|Michael Caine|Heath Ledger|Aaro...,Christopher Nolan,Why So Serious?,Batman raises the stakes in his war on crime. ...,152,Drama|Action|Crime|Thriller,DC Comics|Legendary Pictures|Warner Bros.|Syncopy,7/16/2008,8.1,2008,816921825,7,15,67
118,tt0816692,165000000,621752480,Interstellar,Matthew McConaughey|Jessica Chastain|Anne Hath...,Christopher Nolan,Mankind was born on Earth. It was never meant ...,Interstellar chronicles the adventures of a gr...,169,Adventure|Drama|Science Fiction,Paramount Pictures|Legendary Pictures|Warner B...,11/5/2014,8.0,2014,456752480,11,12,35
125,tt2084970,14000000,233555708,The Imitation Game,Benedict Cumberbatch|Keira Knightley|Matthew G...,Morten Tyldum,The true enigma was the man who cracked the code.,Based on the real life story of legendary cryp...,113,History|Drama|Thriller|War,Black Bear Pictures|Bristol Automotive,11/14/2014,8.0,2014,219555708,11,18,46
9,tt2096673,175000000,853708609,Inside Out,Amy Poehler|Phyllis Smith|Richard Kind|Bill Ha...,Pete Docter,Meet the little voices inside your head.,"Growing up can be a bumpy road, and it's no ex...",94,Comedy|Animation|Family,Walt Disney Pictures|Pixar Animation Studios|W...,6/9/2015,8.0,2015,678708609,6,10,112
34,tt3170832,6000000,35401758,Room,Brie Larson|Jacob Tremblay|Joan Allen|Sean Bri...,Lenny Abrahamson,Love knows no boundaries,Jack is a young boy of 5 years old who has liv...,117,Drama|Thriller,Element Pictures|No Trace Camping|A24|Duperele...,10/16/2015,8.0,2015,29401758,10,4,49
1183,tt0993846,100000000,392000694,The Wolf of Wall Street,Leonardo DiCaprio|Jonah Hill|Margot Robbie|Kyl...,Martin Scorsese,EARN. SPEND. PARTY.,A New York stockbroker refuses to cooperate in...,180,Crime|Drama|Comedy,Paramount Pictures|Appian Way|EMJAG Production...,12/25/2013,7.9,2013,292000694,12,23,29
128,tt2267998,61000000,369330363,Gone Girl,Ben Affleck|Rosamund Pike|Carrie Coon|Neil Pat...,David Fincher,You don't know what you've got 'til it's...,With his wife's disappearance having become th...,145,Mystery|Thriller|Drama,Twentieth Century Fox Film Corporation|Regency...,10/1/2014,7.9,2014,308330363,10,9,30
1191,tt2024544,20000000,187000000,12 Years a Slave,Chiwetel Ejiofor|Michael Fassbender|Lupita Nyo...,Steve McQueen,The extraordinary true story of Solomon Northup,"In the pre-Civil War United States, Solomon No...",134,Drama|History,Plan B Entertainment|Regency Enterprises|River...,10/18/2013,7.9,2013,167000000,10,16,61
119,tt2015381,170000000,773312399,Guardians of the Galaxy,Chris Pratt|Zoe Saldana|Dave Bautista|Vin Dies...,James Gunn,All heroes start somewhere.,"Light years from Earth, 26 years after being a...",121,Action|Science Fiction|Adventure,Marvel Studios|Moving Picture Company (MPC)|Bu...,7/30/2014,7.9,2014,603312399,7,23,28
1081,tt0167260,94000000,1118888979,The Lord of the Rings: The Return of the King,Elijah Wood|Ian McKellen|Viggo Mortensen|Liv T...,Peter Jackson,The eye of the enemy is moving.,Aragorn is revealed as the heir to the ancient...,201,Adventure|Fantasy|Action,WingNut Films|New Line Cinema,12/1/2003,7.9,2003,1024888979,12,45,45
1800,tt0209144,9000000,39723096,Memento,Guy Pearce|Carrie-Anne Moss|Joe Pantoliano|Mar...,Christopher Nolan,Some memories are best forgotten.,Suffering short-term memory loss after a head ...,113,Mystery|Thriller,Summit Entertainment|Newmarket Capital Group|T...,10/11/2000,7.9,2000,30723096,10,7,78
370,tt1375666,160000000,825500000,Inception,Leonardo DiCaprio|Joseph Gordon-Levitt|Ellen P...,Christopher Nolan,Your mind is the scene of the crime.,"Cobb, a skilled thief who commits corporate es...",148,Action|Thriller|Science Fiction|Mystery|Adventure,Legendary Pictures|Warner Bros.|Syncopy,7/14/2010,7.9,2010,665500000,7,9,44
872,tt0253474,35000000,120072577,The Pianist,Adrien Brody|Thomas Kretschmann|Frank Finlay|M...,Roman Polanski,Music was his passion. Survival was his master...,The Pianist is a film adapted from the biograp...,150,Drama|War,Bac Films|Canal+Polska|Heritage Films|Studio B...,9/24/2002,7.9,2002,85072577,9,11,39
138,tt2278388,30000000,174600318,The Grand Budapest Hotel,Ralph Fiennes|Tony Revolori|F. Murray Abraham|...,Wes Anderson,A perfect holiday without leaving home.,The Grand Budapest Hotel tells of a legendary ...,99,Comedy|Drama,Fox Searchlight Pictures|Scott Rudin Productio...,2/26/2014,7.9,2014,144600318,2,24,66
1188,tt1798709,23000000,47351251,Her,Joaquin Phoenix|Scarlett Johansson|Rooney Mara...,Spike Jonze,A Spike Jonze Love Story,"In the not so distant future, Theodore, a lone...",126,Romance|Science Fiction|Drama,Annapurna Pictures,12/18/2013,7.8,2013,24351251,12,3,65
28,tt1895587,20000000,88346473,Spotlight,Mark Ruffalo|Michael Keaton|Rachel McAdams|Lie...,Tom McCarthy,Break the story. Break the silence.,The true story of how The Boston Globe uncover...,128,Drama|Thriller|History,Participant Media|Open Road Films|Anonymous Co...,11/6/2015,7.8,2015,68346473,11,9,30
124,tt2245084,165000000,652105443,Big Hero 6,Scott Adsit|Ryan Potter|Daniel Henney|T.J. Mil...,Don Hall|Chris Williams,From the creators of Wreck-it Ralph and Frozen,The special bond that develops between plus-si...,102,Adventure|Family|Animation|Action|Comedy,Walt Disney Pictures|Walt Disney Animation Stu...,10/24/2014,7.8,2014,487105443,10,10,29
177,tt2582846,12000000,305151265,The Fault in Our Stars,Shailene Woodley|Ansel Elgort|Nat Wolff|Laura ...,Josh Boone,One Sick Love Story,Despite the tumor-shrinking medical miracle th...,125,Romance|Drama,Fox 2000 Pictures|Temple Hill Entertainment|TS...,5/16/2014,7.8,2014,293151265,5,22,47
863,tt0167261,79000000,926287400,The Lord of the Rings: The Two Towers,Elijah Wood|Ian McKellen|Viggo Mortensen|Liv T...,Peter Jackson,A New Power Is Rising.,Frodo and Sam are trekking to Mordor to destro...,179,Adventure|Fantasy|Action,WingNut Films|New Line Cinema|The Saul Zaentz ...,12/18/2002,7.8,2002,847287400,12,37,41

# 27. Какие актеры чаще всего снимаются в одном фильме вместе?

In [69]:
answers['27'] = '5. Daniel Radcliffe & Rupert Grint'
# +

ВАРИАНТ 2

In [70]:
data2 = data_cast_exploded2.pivot_table(columns = 'cast', index = 'cast2', values = 'original_title', aggfunc = 'count')
maxVal = 0
maxPair = dict()
i = 1
for cast1, row in data2.items():
    for cast2, val in row.items():
        i += 1
        if cast1 != cast2:
            if val > maxVal:
                maxVal = val
                maxPair[maxVal] = [[cast1, cast2]]
            elif val == maxVal:
                maxPair[maxVal].append([cast1, cast2])

print(maxPair[maxVal])

[['Daniel Radcliffe', 'Emma Watson'], ['Daniel Radcliffe', 'Rupert Grint'], ['Emma Watson', 'Daniel Radcliffe'], ['Emma Watson', 'Rupert Grint'], ['Rupert Grint', 'Daniel Radcliffe'], ['Rupert Grint', 'Emma Watson']]

# Submission

In [71]:
# в конце можно посмотреть свои ответы к каждому вопросу
answers

{'1': '5. Pirates of the Caribbean: On Stranger Tides (tt1298650)',
 '2': '2. Gods and Generals (tt0279111)',
 '3': '3. Winnie the Pooh (tt1449283)',
 '4': '2. 110',
 '5': '1. 107',
 '6': '5. Avatar (tt0499549)',
 '7': '5. The Lone Ranger (tt1210819)',
 '8': '1. 1478',
 '9': '4. The Dark Knight (tt0468569)',
 '10': '5. The Lone Ranger (tt1210819)',
 '11': '3. Drama',
 '12': '1. Drama',
 '13': '5. Peter Jackson',
 '14': '3. Robert Rodriguez',
 '15': '3. Chris Hemsworth',
 '16': '3. Matt Damon',
 '17': '2. Action',
 '18': '1. K-19: The Widowmaker (tt0267626)',
 '19': '5. 2015',
 '20': '1. 2014',
 '21': '4. Сентябрь',
 '22': '2. 450',
 '23': '5. Peter Jackson',
 '24': '5. Four By Two Productions',
 '25': '3. Midnight Picture Show',
 '26': '1. Inside Out, The Dark Knight, 12 Years a Slave',
 '27': '5. Daniel Radcliffe & Rupert Grint'}

In [72]:
# и убедиться что ни чего не пропустил)
len(answers)

27